xjob/django_cmdb_project/django_cmdb_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

urlpatterns = [
    url(r'^jobapp/',include('jobapp.urls')),
    url(r'^admin/', admin.site.urls),
]

xjob/django_cmdb_project/jobapp/urls.py
from django.conf.urls import url
from jobapp import views

app_name = "jobapp"

urlpatterns = [
    url(r'^$',views.index,name="index"),
    url(r'^get_app_info/$',views.get_appinfo_from_bking,name="get_app_info"),
    url(r'^get_set_info/$',views.get_setinfo_from_bking,name="get_set_info"),
    url(r'^get_module_info/$',views.get_moduleinfo_from_bking,name="get_module_info"),
    url(r'^target_hosts_info/$',views.target_hosts_info,name="target_hosts_info"),
    url(r'^get_host_detail_info/$',views.get_host_detail_info,name="get_host_detail_info"),
    url(r'^login/$',views.auth_login,name="login"),
    url(r'^login1/$',views.auth_login_new,name="login_new"),
    url(r'^logout/$',views.auth_logout,name="logout"),
    url(r'^get_failure_task_detail_info/$',views.get_failure_task_detail_info,name="get_failure_task_detail_info"),
    url(r'^state_sls_job_execute/$',views.state_sls_job_execute,name="state_sls_job_execute"),
    url(r'^get_job_hosts_task_status/$',views.get_job_hosts_task_status,name="get_job_hosts_task_status"),
    url(r'^get_job_host_task_info/$',views.get_job_host_task_info,name="get_job_host_task_info"),
    url(r'^hostname_base_bking_module/$',views.hostname_base_bking_module,name="hostname_base_bking_module"),
    url(r'^dynamicgroup/manage/$',views.dynamic_group_manage,name="dynamic_group_manage"),
    url(r'^dynamicgroup/show/$',views.dynamic_group_records,name="dynamic_group_show"),
    url(r'^dynamicgroup/get/id/$',views.dynamic_group_record_by_id,name="dynamic_group_record_by_id"),
    url(r'^dynamicgroup/del/id/$',views.dynamic_group_del_record_by_id,name="dynamic_group_del_record_by_id"),
    url(r'^dynamic_group_hosts_info/$',views.dynamic_group_hosts_info,name="dynamic_group_hosts_info"),
    url(r'^saltgroup/manage/$',views.salt_group_manage,name="salt_group_manage"),
    url(r'^saltgroup/all/$',views.salt_group_all,name="salt_group_all"),
    url(r'^saltgroup/get/id/$',views.salt_group_record_by_id,name="salt_group_record_by_id"),
    url(r'^saltgroup/del/id/$',views.salt_group_del_record_by_id,name="salt_group_del_record_by_id"),
    url(r'^salt_group_hosts_info/$',views.salt_group_hosts_info,name="salt_group_hosts_info"),
    url(r'^cmd_run_job_execute/$',views.cmd_run_job_execute,name="cmd_run_job_execute"),
    url(r'^cmd_script_job_execute/$',views.cmd_script_job_execute,name="cmd_script_job_execute"),
    url(r'^upload_file_job_execute/$',views.upload_file_job_execute,name="upload_file_job_execute"),
    url(r'^upload/$',views.upload,name="upload"),
    url(r'^user/files/show/$',views.user_dir_files_list,name="user_files_show"),
    url(r'^get_upload_job_hosts_task_status/$',views.get_upload_job_hosts_task_status,name="get_upload_job_hosts_task_status"),
    url(r'^get_upload_file_progress/$',views.get_upload_file_progress,name="get_upload_file_progress"),
    url(r'^get_script_job_hosts_task_status/$',views.get_script_job_hosts_task_status,name="get_script_job_hosts_task_status"),
    url(r'^audit/$',views.audit,name="audit"),
    url(r'^help/$',views.help,name="help"),
    url(r'^del_file/$',views.del_file,name="del_file"),
    url(r'^shortcut_search_host/$',views.shortcut_search_host,name="shortcut_search_host"),
    url(r'^execuser/name/show/$',views.execuser_name_list,name="execuser_name_show"),
    url(r'^get/customscript/args/$',views.get_script_args,name="get_script_args"),
    url(r'^show/customscript/(?P<page>[\w\-]+)/$',views.get_custom_script_list,name="show_custom_script"),
    url(r'^systemuser/manage/(?P<page>[\w\-]+)/$',views.get_system_user_list,name="system_user_manage"),
    url(r'^systemuser/save/$',views.system_user_save,name="system_user_save"),
    url(r'^systemuser/del/$',views.system_user_del,name="system_user_del"),
    url(r'^create/customscript/$',views.create_custom_script,name="create_custom_script"),
    url(r'^edit/customscript/(?P<id>[\w\-]+)/$',views.edit_custom_script,name="edit_custom_script"),
    url(r'^all/customscript/$',views.custom_scripts_all,name="custom_scripts_all"),
    url(r'^save/customscript/$',views.save_custom_script,name="save_custom_script"),
    url(r'^del/customscript/$',views.del_custom_script,name="del_custom_script"),
]

xjob/django_cmdb_project/jobapp/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class DynamicGroup(models.Model):
	GroupName = models.CharField(max_length=128,unique=True)
	GroupMembers = models.TextField()


class SaltGroup(models.Model):
	GroupName = models.CharField(max_length=128,unique=True)
	GroupExpr = models.TextField()


class action_audit(models.Model):
	jid = models.CharField(max_length=255,unique=True)
	user = models.CharField(max_length=50)


class ExecUser(models.Model):
	user = models.CharField(max_length=50,unique=True)


class CustomScript(models.Model):
	script_name = models.CharField(max_length=80,unique=True)
	author = models.CharField(max_length=50)
	editor = models.CharField(max_length=50)
	script_code = models.TextField()
	script_args = models.CharField(max_length=80,null=True,blank=True)
	script_type = models.CharField(max_length=15)
	comment = models.TextField(null=True,blank=True) 

	def __unicode__(self):
		return self.script_name








	

xjob/django_cmdb_project/jobapp/views.py
# -*- encoding:utf-8 -*-
#--------------------------------
# @Date    : 2017-05-10 15:00
# @Author  : wye
# @Version : v1.0
# @Desrc   : job control app views
# -------------------------------- 

from django.shortcuts import render
from django.http import HttpResponse,JsonResponse,HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger

from jobapp.models import DynamicGroup , SaltGroup , action_audit , ExecUser , CustomScript

import os
import sys
import time
import json
import MySQLdb
from salt_api_sdk import *
from bk_cmdb_api import *

reload(sys)
sys.setdefaultencoding('utf-8')

# -----------------------------------------
# MYSQL SERVER INFO
# -----------------------------------------
MysqlServer = "172.30.33.170"
MysqlUser = "salt"
MysqlPasswd = "salt"
MysqlDB = "salt_job_sys"
# -----------------------------------------


def execute_sql(sql):
    try:
        DBConn = MySQLdb.connect(host=MysqlServer,user=MysqlUser,passwd=MysqlPasswd)
        DBCursor = DBConn.cursor()
        DBConn.select_db(MysqlDB)
        RecordNums = DBCursor.execute(sql)
        if RecordNums == 0 or RecordNums == None:
            RecordNums = 0
            RecordSets = ()
        else:
           RecordSets = DBCursor.fetchall()
           DBConn.commit()
        return RecordNums , RecordSets
    except Exception,e:
        print (" Execute sql error,error is %s"%e)
    finally:
        DBConn.close()
        DBCursor.close()



def get_recent_failure_tasks_info(num=10):

    sql = 'select fun,jid,id,alter_time from salt_returns  \n \
           where fun <> "runner.jobs.active"  \n \
           and fun <> "saltutil.running"  \n \
           and success=0 order by jid desc limit 0,%s'%num

    recent_failure_tasks_nums,recent_failure_tasks_records_tuple =  execute_sql(sql)
    return recent_failure_tasks_records_tuple



def get_recent_failure_tasks_nums():

    sql = 'select count(*) from salt_returns  \n \
           where fun <> "runner.jobs.active"  \n \
           and fun <> "saltutil.running"  \n \
           and success=0'

    _ , Records_tuple = execute_sql(sql)
    recent_failure_tasks_nums = Records_tuple[0][0]
    return recent_failure_tasks_nums



def get_recent_succss_tasks_info(num=10):
    sql = 'select fun,jid,id,alter_time from salt_returns where success=1 and fun="%s" or fun="%s" or fun="%s" order by jid desc limit 0,%s'%("cmd.run","state.sls","cp.get_file",num)
    recent_success_tasks_nums,recent_success_tasks_records_tuple =  execute_sql(sql)
    # recent_success_tasks_records = {}
    # if recent_success_tasks_nums != 0:    
    #     for i in range(recent_success_tasks_nums):
    #         recent_success_tasks_records[i+1] = recent_success_tasks_records_tuple[i]

    # return recent_success_tasks_records
    return recent_success_tasks_records_tuple



def get_recent_success_tasks_nums():
    sql = "select count(*) from salt_returns where success=1"
    _ , Records_tuple = execute_sql(sql)
    recent_success_tasks_nums = Records_tuple[0][0]
    return recent_success_tasks_nums



def get_recent_all_jobs_nums():
    sql = "select count(*) from jids"
    _ , Records_tuple = execute_sql(sql)
    recent_all_jobs_nums = Records_tuple[0][0]
    return recent_all_jobs_nums



def get_job_host_task_status(host,jid):
    sql = "select full_ret from salt_returns where jid='%s' and id='%s'"%(jid,host)
    Records_num, Records_tuple = execute_sql(sql)
    if Records_num == 0 or Records_num == None:
        status = None
    else:
        status = json.loads(Records_tuple[0][0])['retcode']

    return status



def get_upload_job_host_task_status(host,jid):
    sql = "select full_ret from salt_returns where jid='%s' and id='%s'"%(jid,host)
    Records_num, Records_tuple = execute_sql(sql)
    if Records_num == 0 or Records_num == None:
        status = None
    else:
        status = json.loads(Records_tuple[0][0])['return']

    return status



def get_script_job_host_task_status(host,jid):
    sql = "select full_ret from salt_returns where jid='%s' and id='%s'"%(jid,host)
    Records_num, Records_tuple = execute_sql(sql)
    if Records_num == 0 or Records_num == None:
        status = None
    else:
        status = json.loads(Records_tuple[0][0])['return']

    return status



def job_host_task_info(host,jid):
    sql = "select full_ret from salt_returns where jid='%s' and id='%s'"%(jid,host)
    _, Records_tuple = execute_sql(sql)
    return json.loads(Records_tuple[0][0])


def write_audit_info(jid,user):
    audit_info_obj = action_audit(jid=jid,user=user)
    audit_info_obj.save()



def get_jid_info(jid):
    sql = "select * from jids where jid='%s'"%jid
    Records_num, Records_tuple = execute_sql(sql)
    if Records_num != 0 and Records_num != None:
        return Records_tuple
    else:
        return None


@login_required
def index(request):    
    resp_info = {}
    #resp_info['recent_all_jobs_nums'] = get_recent_all_jobs_nums()
    #resp_info['recent_success_tasks_nums'] = get_recent_success_tasks_nums()
    #resp_info['recent_failure_tasks_nums'] = get_recent_failure_tasks_nums()
    resp_info['recent_failure_tasks_info'] = get_recent_failure_tasks_info(10)
    resp_info['recent_succss_tasks_info'] = get_recent_succss_tasks_info(10)
    #resp_info['running_jobs_nums'],resp_info['running_jobs_info'] = get_running_jobs_info()
    resp_info['last_days'] = get_keep_jobs_time()

    return render(request,'jobapp/index.html',resp_info)


@login_required
def get_appinfo_from_bking(request):
    appinfo = get_app_info()
    return JsonResponse(appinfo,safe=False)


@login_required
def get_setinfo_from_bking(request):
    app_field_name = request.GET['filter[filters][0][field]']
    app_id = request.GET['filter[filters][0][value]']
    setinfo = get_set_info(app_id)
    return JsonResponse(setinfo,safe=False)



@login_required
def get_moduleinfo_from_bking(request):
    set_name = request.GET['filter[filters][0][field]']
    set_id = request.GET['filter[filters][0][value]']
    moduleinfo = get_module_info(set_id)
    return JsonResponse(moduleinfo,safe=False)


@login_required
def target_hosts_info(request):
    target_hosts_info = {}
    appid = request.GET['app'].split("_")[0]
    appname = request.GET['app'].split("_")[1]

    setid = request.GET['set'].split("_")[0]
    setname = request.GET['set'].split("_")[1]

    moduleid = request.GET['module'].split("_")[0]
    modulename = request.GET['module'].split("_")[1]
    
    target_hosts_info["appname"] = appname
    target_hosts_info["setname"] = setname
    target_hosts_info["modulename"] = modulename

    hosts_list = get_hosts_info_by_module(appid,setid,moduleid)

    # -------------
    hostnames_list = []
    for host1 in hosts_list:
        hostnames_list.append(host1['HostName'])

    hosts_status = get_hosts_status(hostnames_list)
    # -------------

    for host in hosts_list:
        host['status'] = hosts_status.get(host['HostName'])
        if host.get('status'):
            host_meta_info = get_host_meta_info(host['HostName'])
            host['osname_salt'] = host_meta_info['os'] + " " + host_meta_info['osrelease']
            host['ip_salt'] = '|'.join(host_meta_info['ipv4'])
        else:
            pass

    target_hosts_info['hosts'] = hosts_list
    target_hosts_info['GroupName'] = "%s/%s/%s"%(appname,setname,modulename)
    target_hosts_info['datasource'] = "Cmdb"

    return render(request,"jobapp/salt_group_hosts_info.html",target_hosts_info)


def hostname_base_bking_module(request):

    appid = request.GET['appid']
    setid = request.GET['setid']
    moduleid = request.GET['moduleid']
    hosts_list = get_hosts_info_by_module(appid,setid,moduleid)

    hostname_list = []

    for host in hosts_list:
        hostname_list.append(host['HostName'])

    #hostname_list = [{"hostname":"wer","hostid":"234"}]

    return JsonResponse(hostname_list,safe=False)



@login_required
def get_host_detail_info(request):
    hostname = request.GET['hostname']
    host_meta_info = get_host_meta_info(hostname)
    host_meta_info['osname_salt'] = host_meta_info['os'] + " " + host_meta_info['osrelease']
    host_meta_info['ip_salt'] = '|'.join(host_meta_info['ipv4'])

    return render(request,'jobapp/host_detail.html',{"host_detail_info":host_meta_info})




def auth_login(request):
    context = {}
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('jobapp:index'))
            else:
                context['error_info'] = "%s ACCOUNT IS DISABLED!"%username
        else:
            context['error_info'] = "INVALID ACCOUNT!"
    

    return render(request,'jobapp/login.html',context)

def auth_login_new(request):
    import redis,re
    try:
        ci_session = request.COOKIES['ci_session']
        find_key = 'ci_session:' +ci_session
    except:
        return HttpResponse("Login has expired,please login again")
    if find_key:
        redis_conn = redis.Redis(host='172.30.33.102',port=6379,decode_responses=True)
        res = redis_conn.get(find_key)
        if res and res.find('username|s:') != -1 and res.find('chinese_name|s:') != -1:
            username = re.split(r'(?:";chinese_name)',res)[0].split('"')[-1]
            password = 'my password'
            conn1 = MySQLdb.connect(host='172.30.33.170',user='cmdb',passwd='cmdb',db='cmdb_job_sys',port=3306)
            cursor1 = conn1.cursor()
            sql1 = "select is_active from auth_user where username='%s'"%username
            cursor1.execute(sql1)

xjob/django_cmdb_project/templates/jobapp/custom_script_show.html
{% extends 'jobapp/base.html' %}
{% load staticfiles %}

{% block title_block %}
    CustomScript
{% endblock %}

{% block extrahead_block %}
   <script src="{% static 'codemirror-5.14.2/lib/codemirror.js' %}"></script>
   <script src="{% static 'codemirror-5.14.2/mode/shell/shell.js' %}"></script>
   <script src="{% static 'codemirror-5.14.2/mode/python/python.js' %}"></script>
   <script src="{% static 'codemirror-5.14.2/addon/display/fullscreen.js' %}"></script>

   <link rel="stylesheet" href="{% static 'codemirror-5.14.2/lib/codemirror.css' %}" />
   <link rel="stylesheet" href="{% static 'codemirror-5.14.2/theme/erlang-dark.css' %}" />
   <link rel="stylesheet" href="{% static 'codemirror-5.14.2/addon/display/fullscreen.css' %}" />
{% endblock %}

{% block main_block%}
   
    <div style="margin-top:6px;">
        <!-- <h6 style="color: rgb(0, 132, 228)">Custom Scripts</h6> -->
        <a  type="button" class="btn btn-primary" id="script_create_btn" href="{% url 'jobapp:create_custom_script' %}">创建脚本</a>
    </div>
    <div class="table-responsive" style="margin-top:10px;">
        <table class="table table-striped">
            <thead>
                <tr>
                    <td>ID</td>
                    <td>ScriptName</td>
                    <td>Author</td>
                    <td>Editor</td>
                    <td>ScriptType</td>
                    <td>Manage</td>
                </tr>
            </thead>
            <tbody>

            {% for item in scripts %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.script_name }}</td>
                    <td>{{ item.author }}</td>
                    <td>{{ item.editor }}</td>
                    <td>{{ item.script_type }}</td>
                    <td>
                        <a class="btn btn-outline-success my-2 my-sm-0"  role="button" val="{{ item.id }}" name="script_edit_btn" href="{% url 'jobapp:edit_custom_script' item.id %}" >编辑</a>
                        <a class="btn btn-outline-success my-2 my-sm-0"  role="button" val="{{ item.id }}" name="script_delete_btn">删除</a>
                    </td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
    <div>
        <nav>
        <ul class="pagination justify-content-end">
            
            {% if scripts.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'jobapp:show_custom_script' scripts.previous_page_number %}">Previous</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">Previous</a>
                </li>
            {% endif %}

            {% for i in scripts.paginator.page_range %}
                {% if i == scripts.number %}
                    <li class="page-item active">
                        <a class="page-link" href="{% url 'jobapp:show_custom_script' i %}">{{i}}</a>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="{% url 'jobapp:show_custom_script' i %}">{{i}}</a>
                    </li>
                {% endif %}
            {% endfor %}

            {% if scripts.has_next %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'jobapp:show_custom_script' scripts.next_page_number %}">Next</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">Next</a>
                </li>
            {% endif %}

        </ul>
        </nav>
    </div>

    <div id="dialog">
        <input type="hidden" id="script_id">
    </div>

    <script type="text/javascript">
        $(document).ready(function(){

            var dialog = $("#dialog");
            var script_id = ""
            dialog.kendoDialog({
                width: "400px",
                title: "Custom Scripts Manage",
                closable: true,
                modal: true,
                content: "是否确定删除这个脚本?",
                actions: [
                   { text: "确认", action: onOK},
                   { text: "取消"}
                ]
            });

            function onOK(e) {

                $.get("{% url 'jobapp:del_custom_script' %}",{id:script_id},function(){
                     window.location.reload()
                })
            }
 
            dialog.data("kendoDialog").close();

            $('a[name="script_delete_btn"]').click(function(){
                script_id = $(this).attr("val")
                dialog.data("kendoDialog").open();
            })

        })
    </script>

{% endblock %}

xjob/django_cmdb_project/templates/jobapp/failure_task_detail.html
{% if failure_task_record %}

<table class="table table-striped table-condensed table-border">
           <tr>
               <td>JID:</td>
               <td>{{ failure_task_record.jid }}</td>
           </tr>
           <tr>
               <td>目标:</td>
               <td>{{ failure_task_record.id }}</td>
           </tr>
           <tr>
               <td>函数:</td>
               <td>{{ failure_task_record.fun }}</td>
           </tr>
           <tr>
               <td>参数:</td>
               <td>{{ failure_task_record.fun_args }}</td>
           </tr>
           <tr>
               <td>返回代码:</td>
               <td>{{ failure_task_record.retcode }}</td>
           </tr>
           <tr>
               <td>返回数据:</td>
               <td>{{ failure_task_record.return }}</td>
           </tr>
</table>

{% endif %}

xjob/django_cmdb_project/templates/jobapp/login.html
<!DOCTYPE html>
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">

    <title>
    Login
    </title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css'%}" rel="stylesheet">

    <!-- for kendoui -->

    <script src="{% static 'kendoui/js/jquery.min.js' %}"></script> 
    <link rel="stylesheet" href="{% static 'kendoui/styles/kendo.common.min.css' %}" />
    <link rel="stylesheet" href="{% static 'kendoui/styles/kendo.default.min.css' %}" />
    <link rel="stylesheet" href="{% static 'kendoui/styles/kendo.default.mobile.min.css' %}" />
    <script src="{% static 'kendoui/js/kendo.core.min.js' %}"></script>
    <script src="{% static 'kendoui/js/kendo.ui.core.min.js' %}"></script>
    
    
</head>
<body>
<div class="row">
<div class="col-md-5"></div>
<div class="col-md-2">
      
      <form class="form-signin" id="login_form" method="post" action="{% url 'jobapp:login' %}">
        {% csrf_token %}
        <h2 class="form-signin-heading" align="center">作业系统 V1.6</h2>
        <h5 class="form-signin-heading">{{ error_info }}</h5>
        <label for="inputUsername" class="sr-only">Username</label>
        <input type="text" id="inputUsername" class="form-control" placeholder="Username" name="username" required autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Password" name="password" required>
        <div align="center">
            Authentication Is Based On LDAP
            <h6 class="form-signin-heading" align="center">已接入生产，操作需谨慎！</h6>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>
      

</div>
<div class="col-md-5"></div>
</div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/tether.min.js' %}"></script>
    <!-- <script src="{% static 'js/jquery.min.js' %}"></script> -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jobapp.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
    <script>
      $(function () { $("[data-toggle='tooltip']").tooltip(); });
    </script>
</body>
</html>

xjob/django_cmdb_project/templates/jobapp/system_user_manage.html
{% extends 'jobapp/base.html' %}
{% load staticfiles %}

{% block title_block %}
    CustomScript
{% endblock %}


{% block main_block%}
   
    <div style="margin-top:6px;">
        <!-- <h6 style="color: rgb(0, 132, 228)">Custom users</h6> -->
        <input id="users_manage" style="width: 200px;" />
    </div>
    <div class="table-responsive" style="margin-top:10px;">
        <table class="table table-striped">
            <thead>
                <tr>
                    <td>ID</td>
                    <td>UserName</td>
                    <td>Manage</td>
                </tr>
            </thead>
            <tbody>

            {% for item in users %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.user }}</td>
                    <td>
                        <a class="btn btn-outline-success my-2 my-sm-0"  role="button" val="{{ item.id }}" name="user_delete_btn">删除</a>
                    </td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
    <div>
        <nav>
        <ul class="pagination justify-content-end">
            
            {% if users.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'jobapp:system_user_manage' users.previous_page_number %}">Previous</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">Previous</a>
                </li>
            {% endif %}

            {% for i in users.paginator.page_range %}
                {% if i == users.number %}
                    <li class="page-item active">
                        <a class="page-link" href="{% url 'jobapp:system_user_manage' i %}">{{i}}</a>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="{% url 'jobapp:system_user_manage' i %}">{{i}}</a>
                    </li>
                {% endif %}
            {% endfor %}

            {% if users.has_next %}
                <li class="page-item">
                    <a class="page-link" href="{% url 'jobapp:system_user_manage' users.next_page_number %}">Next</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">Next</a>
                </li>
            {% endif %}

        </ul>
        </nav>
    </div>

    
    <div class="modal fade" id="system_user_manage_window" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true" data-backdrop="static" data-keyboard="false">
      <div class="modal-dialog">
        <form method="post" action="{% url 'jobapp:system_user_save' %}">
        {% csrf_token %}
        <div class="modal-content">
          <div class="modal-header">
            <h6 class="modal-title" id="myModalLabel1">系统用户管理</h6>
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          </div>
          <div class="modal-body">
            <input type="text" class="form-control" id="system_user_name" name="system_user_name">
            <input id="users" style="width: 400px;" />
          </div>
          <div class="modal-footer">
           <button type="submit" class="btn btn-primary" id="user_save_btn" name="user_save_btn">确认</button>
          </div>
        </div>
        </form>
      </div>
    </div>

    <script type="text/javascript">
        $(document).ready(function(){
            $('a[name="user_edit_btn"]').click(function(){
                var user_name = $(this).attr("val")
                $("#system_user_name").val(user_name)
            })
            $('a[name="user_delete_btn"]').click(function(){
                var user_id = $(this).attr("val")
                $.get("{% url 'jobapp:system_user_del' %}",{id:user_id},function(data) { 
                    window.location.reload()
                })
            })
            $("#user_save_btn").click(function(){
                var val = $("#system_user_name").val()
                if (val == "") {
                    $("#system_user_name").attr("placeholder","请输入用户名!")
                    return false
                }
            })

            $('#system_user_manage_window').on('shown.bs.modal', function() {
               $(document).off('focusin.modal');
            });
        })
    </script>

    <script id="noDataTemplate" type="text/x-kendo-tmpl">
        <div>
            找不到这个用户，你想添加该用户吗 - '#: instance.filterInput.val() #' ?
        </div>
        <br />

        <button class="k-button" onclick="addNew('#: instance.element[0].id #', '#: instance.filterInput.val() #')">add new user</button>
    </script>

{% endblock %}